### ISSUE TITLE
Lima/Colima panic: runtime error: invalid memory address or nil pointer dereference, segmentation violation

### ISSUE THREAD

**Issue by oktvn** [diskfs/go-diskfs#272]
I am experiencing the same error both with LimaVM and Colima on macOS 15.0.1 (24A348) and it appears to be in connecion to this library

```
octavian@Octavians-MacBook-Pro Downloads % colima start \
--profile default \
--activate \
--arch aarch64 \
--cpu 10 \
--disk 48 \
--memory 24 \
--mount ${HOME}:w \
--mount-inotify \
--ssh-agent \
--vm-type vz \
--vz-rosetta \
--verbose

INFO[0000] starting colima                              
INFO[0000] runtime: docker                              
INFO[0002] starting ...                                  context=vm
> Using the existing instance "colima"
> Starting the instance "colima" with VM driver "vz"
> vmType vz: ignoring networks[0]: [Metric]
> [hostagent] panic: runtime error: invalid memory address or nil pointer dereference
> [hostagent] [signal SIGSEGV: segmentation violation code=0x2 addr=0xf8 pc=0x105478e44]
> [hostagent] goroutine 1 [running]:
> [hostagent] github.com/diskfs/go-diskfs/filesystem/iso9660.walkTree.func1({0x1400073f570, 0x68}, {0x105da9808, 0x1400072b600}, {0x0?, 0x0?})
> [hostagent] 	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/diskfs/go-diskfs@v1.4.1/filesystem/iso9660/finalize.go:948 +0x344
> [hostagent] path/filepath.walkDir({0x1400073f570, 0x68}, {0x105da9808, 0x1400072b600}, 0x140003a8ca0)
> [hostagent] 	/opt/homebrew/Cellar/go/1.23.3/libexec/src/path/filepath/path.go:310 +0x44
> [hostagent] path/filepath.walkDir({0x140005902a0, 0x64}, {0x105da9840, 0x140005e5ba0}, 0x140003a8ca0)
> [hostagent] 	/opt/homebrew/Cellar/go/1.23.3/libexec/src/path/filepath/path.go:332 +0x21c
> [hostagent] path/filepath.WalkDir({0x140005902a0, 0x64}, 0x140003a8ca0)
> [hostagent] 	/opt/homebrew/Cellar/go/1.23.3/libexec/src/path/filepath/path.go:400
> [hostagent] 0x78
> [hostagent] github.com/diskfs/go-diskfs/filesystem/iso9660.walkTree({0x140005902a0, 0x64})
> [hostagent] 	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/diskfs/go-diskfs@v1.4.1/filesystem/iso9660/finalize.go:917 +0x98
> [hostagent] github.com/diskfs/go-diskfs/filesystem/iso9660.(*FileSystem).Finalize(0x140005315f0, {0xf0?
> [hostagent] , 0x15?, 
> [hostagent] ?, {0x105891e7c?, 0x105d98df8?}}
> [hostagent] 	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/diskfs/go-diskfs@v1.4.1/filesystem/iso9660/finalize.go:480
> [hostagent]  +0x240
> [hostagent] github.com/lima-vm/lima/pkg/iso9660util.Write(
> [hostagent] 0x140005a7ad0, 0x2f}, {0x105891e7c, 
> [hostagent] }
> [hostagent] , 
> [hostagent] 0x23, 0xd3da?})
> [hostagent] 	/private/tmp/lima-20241203-4758-a0xarl/lima-1.0.2/pkg/iso9660util/iso9660util.go
> [hostagent] github.com/lima-vm/lima/pkg/cidata.GenerateISO9660({0x14000154060, 0x24}, 
> [hostagent] {0x16b0e78d0?
> [hostagent] , 0x140004762c8
> [hostagent] , 0x104d8c12c?, 0x14000817718?, 
> [hostagent] 0x0, 
> [hostagent] , 0x10
> [hostagent] , ...)
> [hostagent] 	/private/tmp/lima-20241203-4758-a0xarl/lima-1.0.2/pkg/cidata/cidata.go:430 +0x9c0
> [hostagent] github.com/lima-vm/lima/pkg/hostagent.New({0x16b0e78d0, 0x6}, 
> [hostagent] 0x105d98e78, 0x1400004e010
> [hostagent] , 0x14000474310, {0x0, 0x0, 
> [hostagent] 0x0?})
> [hostagent] 	/private/tmp/lima-20241203-4758-a0xarl/lima-1.0.2/pkg/hostagent/hostagent.go
> [hostagent] 141 +
> [hostagent] main.hostagentAction(
> [hostagent] 0x14000014f08, {
> [hostagent] ?})
> [hostagent] :85 +0x4e0
> [hostagent] github.com/spf13/cobra.(*Command).execute(
> [hostagent] 0x1400005aa50
> [hostagent] , 0x5, 0x5
> [hostagent] :985 +0x834
> [hostagent] github.com/spf13/cobra.(*Command).ExecuteC(
> [hostagent] /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x344
> [hostagent] github.com/spf13/cobra.(*Command).Execute(...
> [hostagent] 	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
> [hostagent] main.main()
> [hostagent] 	/private/tmp/lima-20241203-4758-a0xarl/lima-1.0.2/cmd/limactl/main.go:28
> [hostagent] 0x20
> host agent process has exited: exit status 2
FATA[0002] error starting vm: error at 'starting': exit status 1 
```

**Comment by deitch** [comment]
Huh, how interesting. I don't think I knew colima was using go-diskfs. Cool.

I recommend you open an issue with the colima project. If they can track down what triggers it with a reproducible series of steps specific to this library, and can open an issue on specific calls ,we can get a fix in place (or perhaps there already is one). Until then, not much to do here.
